allowDisabledDocker: false
apiVersion: v1
dnsBindAddress: 127.0.0.1:53
dnsDomain: cluster.local
dnsIP: {{ (index .IPs 0).String }}
dnsRecursiveResolvConf: /etc/origin/node/resolv.conf
dockerConfig:
  execHandlerName: ""
imageConfig:
  format: openshift3/ose-${component}:${version}
  latest: false
iptablesSyncPeriod: 30s
kind: NodeConfig
kubeletArguments:
#  cloud-config:
#  - /etc/azure/azure.conf
#  cloud-provider:
#  - azure
  node-labels:
{{- if .Master}}
  - role=master
{{- else}}
  - role=app
{{- end}}
  - logging=true
  - zone=default
masterClientConnectionOverrides:
  acceptContentTypes: application/vnd.kubernetes.protobuf,application/json
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  qps: 100
masterKubeConfig: system:node:{{ .Hostname }}.kubeconfig
networkConfig:
  mtu: 1450
  networkPluginName: redhat/openshift-ovs-multitenant
networkPluginName: redhat/openshift-ovs-multitenant
nodeName: {{ .Hostname }}
podManifestConfig:
proxyArguments:
  proxy-mode:
  - iptables
servingInfo:
  bindAddress: 0.0.0.0:10250
  certFile: server.crt
  clientCA: ca.crt
  keyFile: server.key
#volumeConfig:
#  localQuota:
#    perFSGroup: 512Mi
volumeDirectory: /var/lib/origin/openshift.local.volumes
